apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-argocd
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-argocd
        spec:
          remediationAction: enforce
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: app.k8s.io/v1beta1
                kind: Application
                metadata:
                  name: helmchartargo
                  namespace: policies
                  annotations:
                    apps.open-cluster-management.io/deployables: ''
                spec:
                  componentKinds:
                    - group: apps.open-cluster-management.io
                      kind: Subscription
                  descriptor: {}
                  selector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - helmchartargo
            - complianceType: musthave
              objectDefinition:
                apiVersion: apps.open-cluster-management.io/v1
                kind: Subscription
                metadata:
                  name: helmchartargo-subscription-1
                  namespace: policies
                  annotations: {}
                  labels:
                    app: helmchartargo
                    app.kubernetes.io/part-of: helmchartargo
                    apps.open-cluster-management.io/reconcile-rate: medium
                spec:
                  name: argo-cd
                  channel: argocd/argocd
                  packageOverrides:
                    - packageAlias: argo-cd
                      packageName: argo-cd
            - complianceType: musthave
              objectDefinition:
                apiVersion: apps.open-cluster-management.io/v1
                kind: Channel
                metadata:
                  annotations:
                    apps.open-cluster-management.io/reconcile-rate: medium
                  name: argocd
                  namespace: argocd
                spec:
                  pathname: https://charts.wener.tech
                  type: HelmRepo
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-pod
placementRef:
  name: placement-policy-pod
  kind: Placement
  apiGroup: cluster.open-cluster-management.io
subjects:
- name: policy-argocd
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-pod
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions: []