apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-generator
policyDefaults:
  namespace: policy-generator
  remediationAction: enforce
  severity: medium
policies:
  - name: policy-generator-app
    manifests:
      - path: rendered-manifests.yaml
    placement:
      clusterSelector:
        matchExpressions: [] 
