# # apiVersion: v1
# # kind: Namespace
# # metadata:
# #   name: policy-generator
# ---
# # apiVersion: app.k8s.io/v1beta1
# # kind: Application
# # metadata:
# #   name: policy-generator
# #   namespace: policy-generator
# # spec:
# #   componentKinds:
# #     - group: apps.open-cluster-management.io
# #       kind: Subscription
# #   descriptor: {}
# #   selector:
# #     matchExpressions:
# #       - key: app
# #         operator: In
# #         values:
# #           - policy-generator
# ---
# # apiVersion: apps.open-cluster-management.io/v1
# # kind: Channel
# # metadata:
# #   annotations:
# #     apps.open-cluster-management.io/reconcile-rate: high
# #   name: policy-generator
# #   namespace: policy-generator
# # spec:
# #   type: HelmRepo
# #   pathname: chart/qos-scheduler
# #   insecureSkipVerify: true
# ---
# # apiVersion: apps.open-cluster-management.io/v1
# # kind: Subscription
# # metadata:
# #   annotations:
# #     apps.open-cluster-management.io/git-branch: main
# #     apps.open-cluster-management.io/git-path: kustomize
# #     apps.open-cluster-management.io/reconcile-option: merge
# #   labels:
# #     app: policy-generator
# #   name: policy-generator-subscription
# #   namespace: policy-generator
# # spec:
# #   allow:
# #     - apiVersion: policy.open-cluster-management.io/v1
# #       kinds:
# #         - "*"
# #     - apiVersion: apps.open-cluster-management.io/v1
# #       kinds:
# #         - PlacementRule
# #   channel: policy-generator/policy-generator
# #   placement:
# #     placementRef:
# #       kind: PlacementRule
# #       name: policy-generator-placement
# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: dev
# ---
# apiVersion: apps.open-cluster-management.io/v1
# kind: Channel
# metadata:
#   name: dev-helmrepo
#   namespace: dev
#   annotations:
#     apps.open-cluster-management.io/reconcile-rate: high
# spec:
#   type: HelmRepo
#   pathname: chart/qos-scheduler
#   insecureSkipVerify: true
# ---
# apiVersion: apps.open-cluster-management.io/v1
# kind: Subscription
# metadata:
#   name: nginx-sub
# spec:
#   channel: dev/dev-helmrepo
#   name: ingress-nginx
#   placement:
#     placementRef:
#       kind: Placement
#       name: nginx-placement
#       namespace: default
# ---
# apiVersion: cluster.open-cluster-management.io/v1beta1
# kind: Placement
# metadata:
#   name: nginx-placement
#   namespace: default
# spec:
#   numberOfClusters: 10
#   clusterSets:
#     - default
# ---
# apiVersion: cluster.open-cluster-management.io/v1beta2
# kind: ManagedClusterSetBinding
# metadata:
#   name: default
#   namespace: default
# spec:
#   clusterSet: default
# # apiVersion: apps.open-cluster-management.io/v1
# # kind: PlacementRule
# # metadata:
# #   labels:
# #     app: policy-generator
# #   name: policy-generator-placement
# #   namespace: policy-generator
# # spec:
# #   # clusterConditions:
# #   #   - status: "True"
# #   #     type: ManagedClusterConditionAvailable
# #   clusterSelector:
# #     matchExpressions: []
#       # - key: local-cluster
#       #   operator: In
#       #   values:
#       #     - "true"



apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: demo-helmrepo
  namespace: default
spec:
    type: HelmRepo
    pathname: https://charts.helm.sh/stable/
    insecureSkipVerify: true
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: demo-placement
  namespace: default
spec:
  numberOfClusters: 1
  clusterSets:
    - default
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            purpose: test
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: demo-subscription
  namespace: default
spec:
  channel: default/demo-helmrepo
  name: nginx-ingress
  placement:
    placementRef:
      name: demo-placement
      kind: Placement
  packageOverrides:
  - packageName: nginx-lego
    packageAlias: nginx-lego-simple
    packageOverrides:
    - path: spec
      value:
        defaultBackend:
          replicaCount: 2